### PR TITLE
Update case-transfer.vbs

### LINKED ISSUE #628: Enhancement to Case Transfer script
Auto populate the OFFICE field to always have "001" entered.

I can take this one.

### PR DESCRIPTION
**Pull request by khiestand**
Added the 001 to auto-populate in the OFFICE edit box.

Resolves #628

### CODE REVIEW

**Comment by theVKC** [comment]
Looks great, @khiestand! I'm going to hold a bit until I get some feedback on #628.

**Comment by paschell** [comment]
If you check OFMA (PRISM Office Maintenance) most counties use only 001 as the only office, however in shared counties there are as many as 5.  So I am not sure about auto populating this field if at some time the whole state will be using these scripts.  Just a thought.

**Comment by khiestand** [comment]
@paschell do you know if they are always going to be typing three digits there?  We were running into an issue in Wright where the worker was only entering "01" instead of "001" and then the script doesn't transfer the case.

**Comment by paschell** [comment]
@khiestand  - I believe it is a 3 digit field on PRISM, no exceptions.   

For example: County '083', Southwest Health and Human Services   
(SHHS), currently has five office locations, '001', '002', '003', '004 and '005'.

**Comment by RoberT-1000** [comment]
We should put some data validation on those fields if there are problems with staff entering invalid values.

And, as I recall, there are 5 agencies with multiple Office values:
* Nicollet
* St. Louis
* SWHHS
* Somebody (sorry)
* Somebody else (sorry)

**Comment by theVKC** [comment]
Agreed, folks. We should add data validation. Alternatively, we can set logic based on the county code, right?

**Comment by theVKC** [comment]
I'll be closing this pull request because I just made mass changes. @khiestand, after we have an opportunity to evaluate the suggested changes in #628 (hopefully this week), then we can reopen it. :)

**Pull request closed without merging**
