### PR TITLE
#728: New METS MA interface notes script

### PR DESCRIPTION
**Pull request by khiestand**
This is a new script that notes if the MAO referral was attempted but failed, it will create a FREE caad note and also the option to create a worklist or email to someone regarding this issue.

### CODE REVIEW

**Comment by theVKC** [comment]
@khiestand: any way you can update the complete-list-of-scripts to include this?

**Comment by theVKC** [comment]
@jlmartinone will be updating complete list of scripts. Thanks Jodi!

**Comment by khiestand** [comment]
@theVKC I think this script is now obsolete.  I believe the programming has been fixed on the METS end while I was out on leave.

**Comment by theVKC** [comment]
Shoot. Of course I just pulled in the menu item without this script existing...

@khiestand or @jlmartinone: should I close this and reverse that commit?

**Pull request closed without merging**
