### PR TITLE
#778, #779, #780, #781, #782, #783, #784

### PR DESCRIPTION
**Pull request by KyleNelson-Hennepin**
Changes made:
1.	(#778) Script no longer ends if user inputs invalid caseload info into 2nd dialog box
2.	(#779) Removed extra space in the Excel case number column
3.	(#780) Fixed bug that added an extra row of data to Excel
4.	(#781) Script will now correctly autofit Excel columns after all data is added to Excel
5.	(#782) Enhanced initial dialog box
6.	(#783) Cleaned up several parts of the code
7.	(#783) Fixed tab order on 2nd dialog box
8.	(#783) Formatted financial columns in Excel as numbers
9.	(#783) Removed a custom function that was never called in the script
10.	(#783) Right-aligned last payment date column in Excel
11.	(#784) Fixed bug that would sometimes display an empty column in Excel
12.	(all) Added/updated comments

### CODE REVIEW

**Comment by theVKC** [comment]
@KyleNelson-Hennepin: so normally I don't say this for 1-2 issues... but in a case like this, feel free to just create one overarching issue to address all the ideas for a single script. :) You can use checkboxes to tag all of the parts of it (and as you check them off, it'll even show a progress indicator on the issue, which is really pretty).

No worries about redoing the issues at present, I'll handle it. But just so you know for the future. :)

**Comment by KyleNelson-Hennepin** [comment]
Ok, sounds good! I wasn't sure - it felt a bit odd creating so many issues, but that's what the instructions say so I did it that way. In the future if I do anything like this again, I'll just create one issue.

**Comment by theVKC** [comment]
Normally you're absolutely right. Most of the time we aren't making this many changes on a script though. :)

In any case, I've been thinking about amending those instructions to say create a single issue. Mainly to avoid cross-notification awkwardness.

**Comment by KyleNelson-Hennepin** [comment]
Great! Yep that makes sense to me, I can do that. I was hoping to get this done yesterday but wasn't able to get to it. I'll take care of it tomorrow (Friday).

**Comment by KyleNelson-Hennepin** [comment]
Done!

**Pull request closed without merging**
