### PR TITLE
RE: 721 - Adding supervisor users to globvar

### PR DESCRIPTION
**Pull request by RoberT-1000**
BLIP: This update add a list of supervisors for the agency and a constant that determines whether the user should have additional functionality.

### CODE REVIEW

**Comment by theVKC** [comment]
@RoberT-1000: what scripts will use this functionality? Any yet?

I'll need to modify the installer. Just want to make sure I'm providing space to get all the changes done and changed and whatnot.

**Comment by RoberT-1000** [comment]
Nothing yet. I have a script we are testing that grabs NCP SSNs off NCDE, then navigates to MAXIS to check if they are active on GA or MFIP. Supervisors have the option of creating worklist items for their staff from that output.

I'm also wondering if the changes made via #675 could be aided with this functionality.

**Comment by RoberT-1000** [comment]
I could take a look

**Comment by RoberT-1000** [comment]
@jlmartinone in the decision field, I'm assuming the first option (sent to supervisor) is the only one you want staff picking and then the other three should be made available when the user is a supervisor? I'm a little confused on which areas are explicitly for supervisors. At the moment, there is nothing about this script that stops a user from taking a "supervisory" action, unless PRISM is set up to stop that from happening.

image
****

**Comment by jlmartinone** [comment]
Before I added the "supervisory" part of the script I had the same concern. I spoke with my supervisor. Karen, and she said it is not always a supervisor who approves AMPP.

I hope that helps some.  Please let me know if you have any additional questions.

Thanks!


________________________________

**Pull request merged**
