### PR TITLE
#633: hearing notes - added Paternity to expro drop down list

### LINKED ISSUE #633: Notes: Date of hearing
It was just brought to my attention that the drop down for this script under Motion before the court, there is no option for Paternity when you select Expro.  Can we have this added as a drop down option.  In Stearns all our Paternity go before expro first and them may move to judicial court. Thanks!

### PR DESCRIPTION
**Pull request by KallistaImdieke**
added "paternity" to the hearing type drop down list

### CODE REVIEW

**Comment by KallistaImdieke** [comment]
@theVKC looks like this one may already have the changelog dialog from what I can see? at line 37?

**Comment by theVKC** [comment]
In line 42, can you pop that line down and add another entry with your info?

**Comment by theVKC** [comment]
@KallistaImdieke: can you pop that one changelog line down for me and add another entry with your info? Need to update the changelog in order to wrap this up.

**Comment by KallistaImdieke** [comment]
changes should be made

**Pull request merged**
