### PR TITLE
#618: Switched the "Ok" and "Cancel" buttons

### PR DESCRIPTION
**Pull request by heatherallen**
I only switched the "Ok" and "Cancel" button on the dialog box.

### CODE REVIEW

**Comment by theVKC** [comment]
Hey @heatherallen! Looks like you're using IE for this. Any chance you can switch to Firefox or Chrome and then try again?

**Comment by heatherallen** [comment]
@theVKC I'm working with my supervisor and IT to see if I can get either of those internet options and then I will try again.

**Comment by theVKC** [comment]
"Compatibility mode" might be another option, but I can't test it as I'm not having this issue.

**Comment by theVKC** [comment]
#631 fixes Heather's IE issue. Closing.

**Pull request closed without merging**
