### PR TITLE
#635 Affidavit of Service by Mail Docs Enhancement

### PR DESCRIPTION
**Pull request by KallistaImdieke**
Enhanced the script so that it pulls in if there is an attorney on file for the parties and the date of withdrawal if one. Also pulls in if there are Safety Concerns, Added checkbox to click is service is done by the direction of the County Attorney. Lastly it will update automatically the county in which service is being done and the name of the worker on the case.

### CODE REVIEW

**Comment by heatherallen** [comment]
I don't know if I should open another issue for the bug one of my coworkers discovered on this script.  When she was typing in the Other box there seems to be no ending for the number of characters that you can type in each Other box.  She stated that when she typed over the allotted amount, the Affidavit of Service does not print and she had manually go in and adjust the wording.

**Comment by theVKC** [comment]
Hmmm. @heatherallen, this change to the script isn't live. Is it possible it's the old one doing that?

@KallistaImdieke, care to weigh in?

**Comment by heatherallen** [comment]
@theVKC You might be right!  I just changed the Scott county users to the master branch so I will have them test again :)

**Comment by theVKC** [comment]
@heatherallen: It still isn't live because this is a pull request. You could copy the code into an agency custom version if you'd like (that would actually be super helpful since the dialog changed so much, and I'd like feedback on that from someone who uses it).

**Pull request closed without merging**
